
export const types = {

    uiOpenModal: '[ui] Open modal',
    uiCloseModal: '[ui] Close modal',
    uiOpenPassModal: '[ui] Open Pass modal',
    uiClosePassModal: '[ui] Close Pass modal',
    uiOpenModalArt: '[ui] Open modal Art',
    uiCloseModalArt: '[ui] Close modal Art',

    authCheckingFinish: '[auth] Finish checking login state',
    authStartLogin: '[auth] Start login',
    authLogin: '[auth] Login',
    authStartRegister: '[auth] Start Register',
    authStartStartTokenRenew: '[auth] Start token renew',
    authLogout: '[auth] Logout',

    usuarioSetActive: '[usuario] Set Active',
    usuarioAddNew: '[usuario] Add new',
    usuarioClearActiveUsuario: '[usuario] Clear active usuario',
    usuarioUpdated: '[usuario] Usuario updated',
    usuarioDeleted: '[usuario] Usuario deleted',
    usuarioLoaded: '[usuario] Usuarios loaded',

    clienteSetActive: '[cliente] Set Active',
    clienteAddNew: '[cliente] Add new',
    clienteClearActiveCliente: '[cliente] Clear active cliente',
    clienteUpdated: '[cliente] Cliente updated',
    clienteDeleted: '[cliente] Cliente deleted',
    clienteLoaded: '[cliente] Cliente loaded',

    ventaSetActive: '[venta] Set Active',
    ventaAddNew: '[venta] Add new',
    ventaClearActiveVenta: '[venta] Clear active venta',
    ventaUpdated: '[venta] Venta updated',
    ventaDeleted: '[venta] Venta deleted',
    ventaLoaded: '[venta] Venta loaded',
    ventaLoadedOne: '[venta] Venta loaded one',

    remitoHSetActive: '[remitoh] Set Active',
    remitoHAddNew: '[remitoh] Add new',
    remitoHClearActiveRemito: '[remitoh] Clear active remito',
    remitoHUpdated: '[remitoh] Remito updated',
    remitoHDeleted: '[remitoh] Remito deleted',
    remitoHLoaded: '[remitoh] Remito loaded',
    remitoHLoadedOne: '[remitoh] Remito loaded one',

    remitoTSetActive: '[remitot] Set Active',
    remitoTAddNew: '[remitot] Add new',
    remitoTClearActiveRemito: '[remitot] Clear active remito',
    remitoTUpdated: '[remitot] Remito updated',
    remitoTDeleted: '[remitot] Remito deleted',
    remitoTLoaded: '[remitot] Remito loaded',
    remitoTLoadedOne: '[remitot] Remito loaded one',

    stockSetActive: '[stock] Set Active',
    stockAddNew: '[stock] Add new',
    stockClearActiveStock: '[stock] Clear active stock',
    stockUpdated: '[stock] Stock updated',
    stockDeleted: '[stock] Stock deleted',
    stockLoaded: '[stock] Stock loaded',
    stockLoadedOne: '[stock] Stock loaded one',

    solTSetActive: '[solt] Set Active',
    solTAddNew: '[solt] Add new',
    solTClearActiveSol: '[solt] Clear active solicitud',
    solTUpdated: '[solt] Solt updated',
    solTDeleted: '[solt] Solt deleted',
    solTLoaded: '[solt] Solt loaded',
    solTLoadedOne: '[solt] Solt loaded one',

}